options(stringsAsFactors = FALSE)
options(survey.lonely.psu = "adjust")

suppressPackageStartupMessages({
  library(survey)
  library(jsonlite)
})

out_dir <- "nutrition_stage/output_c_n14"
dat <- read.csv(file.path(out_dir, "c_n14_analysis_core.csv"), na.strings=c("","NA"))
num_vars <- c("age","sex","race","education","pir","weight","psu_u","strata_u","mean_kcal","mean_protein","mean_potassium","mean_sodium","mean_magnesium","day1_sodium","day2_sodium","sodium_density","serum_sodium","serum_potassium","serum_chloride","serum_bicarbonate","creatinine","egfr","albumin","bmi","body_weight","height","diabetes","hypertension","cvd","heart_failure","wasting_days","hyponatremia_135","strict_hyponatremia_134","low_normal_na_138","log_sodium_intake")
for(v in intersect(num_vars,names(dat))) dat[[v]]<-suppressWarnings(as.numeric(dat[[v]]))
for(v in c("chronic_thiazide","raas","ppi","complete_case")) dat[[v]]<-as.logical(dat[[v]])
dat$cycle<-factor(dat$cycle,levels=c("E","F","G","H","I","J"));dat$period<-factor(dat$period,levels=c("discovery","validation"));dat$sex<-factor(dat$sex,levels=c(1,2),labels=c("male","female"));dat$race<-factor(dat$race);dat$exposure<-factor(dat$exposure,levels=c("higher","low"))
make_design<-function(d)svydesign(ids=~psu_u,strata=~strata_u,weights=~weight,nest=TRUE,data=d)
safe_effect<-function(m,term,expit=FALSE){cf<-coef(m);if(!(term%in%names(cf)))return(rep(NA_real_,4));se<-sqrt(diag(vcov(m)))[term];est<-unname(cf[term]);p<-tryCatch(unname(summary(m)$coefficients[term,ncol(summary(m)$coefficients)]),error=function(e)NA_real_);z<-c(est,est-1.96*se,est+1.96*se,p);if(expit)z[1:3]<-exp(z[1:3]);z}
clean_vars<-function(d,vars){out<-vars;for(v in intersect(c("sex","race","cycle"),out))if(length(unique(d[[v]][!is.na(d[[v]])]))<2)out<-setdiff(out,v);out}
model_rows<-list();append_model<-function(scope,name,m,term="exposurelow",expit=FALSE){z<-safe_effect(m,term,expit);model_rows[[length(model_rows)+1]]<<-data.frame(candidate_code="C-N14",scope=scope,model=name,term=term,estimate=z[1],lower=z[2],upper=z[3],p=z[4],n=nrow(m$model));z}
fit_scope<-function(d,scope){d<-droplevels(d[d$complete_case&!is.na(d$exposure),,drop=FALSE]);if(nrow(d)<200||sum(d$exposure=="low")<40||sum(d$hyponatremia_135==1)<15||nlevels(d$exposure)<2)return(NULL);des<-make_design(d);crude<-clean_vars(d,c("exposure","cycle"));full<-clean_vars(d,c("exposure","age","sex","race","bmi","egfr","diabetes","hypertension","cvd","mean_kcal","mean_protein","mean_potassium","mean_magnesium","raas","ppi","pir","cycle"));f<-function(y,x)as.formula(paste(y,"~",paste(x,collapse=" + ")));m1<-svyglm(f("hyponatremia_135",crude),design=des,family=quasipoisson(link="log"));m2<-svyglm(f("hyponatremia_135",crude),design=des,family=gaussian());m3<-svyglm(f("serum_sodium",crude),design=des,family=gaussian());m4<-svyglm(f("hyponatremia_135",full),design=des,family=quasipoisson(link="log"));m5<-svyglm(f("hyponatremia_135",full),design=des,family=gaussian());m6<-svyglm(f("serum_sodium",full),design=des,family=gaussian());m7<-svyglm(f("strict_hyponatremia_134",full),design=des,family=quasipoisson(link="log"));append_model(scope,"crude_hyponatremia_pr",m1,expit=TRUE);append_model(scope,"crude_hyponatremia_rd",m2);append_model(scope,"crude_serum_na_difference",m3);pr<-append_model(scope,"adjusted_hyponatremia_pr",m4,expit=TRUE);rd<-append_model(scope,"adjusted_hyponatremia_rd",m5);nad<-append_model(scope,"adjusted_serum_na_difference",m6);spr<-append_model(scope,"adjusted_strict_hyponatremia_pr",m7,expit=TRUE);list(data=d,pr=pr,rd=rd,nad=nad,spr=spr)}
primary<-fit_scope(dat,"overall");discovery<-fit_scope(dat[dat$period=="discovery",],"discovery");validation<-fit_scope(dat[dat$period=="validation",],"validation");if(is.null(primary))stop("Primary C-N14 model could not be estimated")
miss<-droplevels(dat[!is.na(dat$exposure)&!is.na(dat$age)&!is.na(dat$sex)&!is.na(dat$race),,drop=FALSE]);mv<-clean_vars(miss,c("exposure","age","sex","race","cycle"));mm<-svyglm(as.formula(paste("I(complete_case) ~",paste(mv,collapse=" + "))),design=make_design(miss),family=quasibinomial());mz<-safe_effect(mm,"exposurelow",TRUE);missingness_df<-data.frame(term="exposurelow",odds_ratio=mz[1],lower=mz[2],upper=mz[3],p=mz[4])
weighted_quantile<-function(x,w,p){ok<-is.finite(x)&is.finite(w)&w>0;x<-x[ok];w<-w[ok];o<-order(x);x<-x[o];w<-w[o];cw<-cumsum(w)/sum(w);sapply(p,function(q)x[which(cw>=q)[1]])}
rcs_basis<-function(x,k){p3<-function(z)pmax(z,0)^3;den<-(k[length(k)]-k[1])^2;h<-sapply(seq_len(length(k)-2),function(j)(p3(x-k[j])-p3(x-k[length(k)-1])*(k[length(k)]-k[j])/(k[length(k)]-k[length(k)-1])+p3(x-k[length(k)])*(k[length(k)-1]-k[j])/(k[length(k)]-k[length(k)-1]))/den);colnames(h)<-paste0("rcs",seq_len(ncol(h)));h}
nl<-primary$data;k<-weighted_quantile(nl$log_sodium_intake,nl$weight,c(.05,.35,.65,.95));b<-rcs_basis(nl$log_sodium_intake,k);nl$xlin<-nl$log_sodium_intake;nl$rcs1<-b[,1];nl$rcs2<-b[,2];nv<-clean_vars(nl,c("xlin","rcs1","rcs2","age","sex","race","bmi","egfr","diabetes","hypertension","cvd","mean_kcal","mean_protein","mean_potassium","mean_magnesium","raas","ppi","pir","cycle"));fn<-function(y)as.formula(paste(y,"~",paste(nv,collapse=" + ")));dn<-make_design(nl);np<-svyglm(fn("hyponatremia_135"),design=dn,family=quasipoisson(link="log"));ns<-svyglm(fn("serum_sodium"),design=dn,family=gaussian());nonlinear_df<-rbind(data.frame(outcome="hyponatremia_135",n=nrow(nl),p_nonlinear=unname(regTermTest(np,~rcs1+rcs2)$p),knots_mg_day=paste(round(exp(k)),collapse="|")),data.frame(outcome="serum_sodium",n=nrow(nl),p_nonlinear=unname(regTermTest(ns,~rcs1+rcs2)$p),knots_mg_day=paste(round(exp(k)),collapse="|")))
sens_rows<-list();run_sens<-function(label,d,low=2000,high=2500,outcome="hyponatremia_135",day1=FALSE,extra=NULL){d$intake<-if(day1)d$day1_sodium else d$mean_sodium;d$exp2<-ifelse(d$intake<low,"low",ifelse(d$intake>=high,"higher",NA_character_));d<-droplevels(d[!is.na(d$exp2),,drop=FALSE]);d$exp2<-factor(d$exp2,levels=c("higher","low"));vars<-clean_vars(d,c("age","sex","race","bmi","egfr","diabetes","hypertension","cvd","mean_kcal","mean_protein","mean_potassium","mean_magnesium","raas","ppi","pir","cycle"));if(!is.null(extra))vars<-c(vars,extra);req<-setdiff(vars,"cycle");d<-droplevels(d[complete.cases(d[,req,drop=FALSE]),,drop=FALSE]);vars<-clean_vars(d,vars);if(nrow(d)<150||sum(d$exp2=="low")<30||sum(d[[outcome]]==1)<10||nlevels(d$exp2)<2)return(NULL);form<-as.formula(paste(outcome,"~ exp2 +",paste(vars,collapse=" + ")));des<-make_design(d);mpr<-svyglm(form,design=des,family=quasipoisson(link="log"));mrd<-svyglm(form,design=des,family=gaussian());mna<-svyglm(as.formula(paste("serum_sodium ~ exp2 +",paste(vars,collapse=" + "))),design=des,family=gaussian());zp<-safe_effect(mpr,"exp2low",TRUE);zr<-safe_effect(mrd,"exp2low");zn<-safe_effect(mna,"exp2low");sens_rows[[length(sens_rows)+1]]<<-data.frame(label=label,outcome=outcome,n=nrow(d),key_group_n=sum(d$exp2=="low"),key_group_events=sum(d[[outcome]][d$exp2=="low"]),pr=zp[1],pr_lower=zp[2],pr_upper=zp[3],rd=zr[1],rd_lower=zr[2],rd_upper=zr[3],serum_na_difference=zn[1],na_lower=zn[2],na_upper=zn[3],adverse_direction=is.finite(zp[1])&&is.finite(zr[1])&&is.finite(zn[1])&&zp[1]>1&&zr[1]>0&&zn[1]<0)}
run_sens("primary",dat);run_sens("strict_na_lt_135",dat,outcome="strict_hyponatremia_134");run_sens("low_1800",dat,low=1800);run_sens("higher_3000",dat,high=3000);run_sens("day1",dat,day1=TRUE);run_sens("egfr_ge_60",dat[dat$egfr>=60,]);run_sens("no_raas",dat[!dat$raas,]);run_sens("no_ppi",dat[!dat$ppi,]);run_sens("chronic_30d",dat[dat$chronic_thiazide,]);run_sens("women",dat[dat$sex=="female",]);run_sens("men",dat[dat$sex=="male",]);run_sens("age_65_plus",dat[dat$age>=65,]);run_sens("add_bicarbonate",dat,extra="serum_bicarbonate");for(cy in levels(dat$cycle))run_sens(paste0("leave_out_",cy),dat[dat$cycle!=cy,])
model_df<-do.call(rbind,model_rows);sens_df<-do.call(rbind,sens_rows);write.csv(model_df,file.path(out_dir,"c_n14_models.csv"),row.names=FALSE);write.csv(sens_df,file.path(out_dir,"c_n14_sensitivities.csv"),row.names=FALSE);write.csv(nonlinear_df,file.path(out_dir,"c_n14_nonlinearity.csv"),row.names=FALSE);write.csv(missingness_df,file.path(out_dir,"c_n14_missingness_mechanism.csv"),row.names=FALSE)
prep<-fromJSON(file.path(out_dir,"c_n14_prep_status.json"));pr<-primary$pr;rd<-primary$rd;nad<-primary$nad;dpr<-if(is.null(discovery))rep(NA_real_,4)else discovery$pr;vpr<-if(is.null(validation))rep(NA_real_,4)else validation$pr;drd<-if(is.null(discovery))rep(NA_real_,4)else discovery$rd;vrd<-if(is.null(validation))rep(NA_real_,4)else validation$rd;dna<-if(is.null(discovery))rep(NA_real_,4)else discovery$nad;vna<-if(is.null(validation))rep(NA_real_,4)else validation$nad
sample_gate<-prep$actual_n>=1500;retention_gate<-prep$complete_case_retention>=.8;key_gate<-prep$key_group_n>=500&&prep$key_group_events>=25&&prep$validation_key_group_n>=200&&prep$validation_key_group_events>=10;clinical_gate<-(pr[1]>=1.5&&pr[2]>=1.1&&rd[1]>=.02&&rd[2]>.002)||(nad[1]<=-.7&&nad[3]<=-.2);temporal_gate<-all(is.finite(c(dpr[1],vpr[1],drd[1],vrd[1],dna[1],vna[1])))&&dpr[1]>1&&vpr[1]>1&&drd[1]>0&&vrd[1]>0&&dna[1]<0&&vna[1]<0;sens_gate<-nrow(sens_df)>=10&&sum(sens_df$adverse_direction,na.rm=TRUE)>=ceiling(.7*nrow(sens_df));nl_gate<-nrow(nonlinear_df)==2&&all(is.finite(nonlinear_df$p_nonlinear));miss_gate<-is.finite(missingness_df$odds_ratio[1]);pass<-all(c(sample_gate,retention_gate,key_gate,clinical_gate,temporal_gate,sens_gate,nl_gate,miss_gate))
status<-list(candidate_code="C-N14",data_analysis_completed=TRUE,prep=prep,primary=list(adjusted_pr=list(estimate=pr[1],lower=pr[2],upper=pr[3],p=pr[4]),adjusted_rd=list(estimate=rd[1],lower=rd[2],upper=rd[3],p=rd[4]),adjusted_serum_na_difference=list(estimate=nad[1],lower=nad[2],upper=nad[3],p=nad[4])),discovery=list(pr=dpr[1],rd=drd[1],na_difference=dna[1]),validation=list(pr=vpr[1],rd=vrd[1],na_difference=vna[1]),nonlinearity=nonlinear_df,sensitivity_concordant=sum(sens_df$adverse_direction,na.rm=TRUE),sensitivity_total=nrow(sens_df),gates=list(sample_gate=sample_gate,complete_case_retention_gate=retention_gate,key_group_event_gate=key_gate,clinical_magnitude_precision_gate=clinical_gate,temporal_replication_gate=temporal_gate,sensitivity_direction_gate=sens_gate,nonlinearity_completed=nl_gate,missingness_mechanism_completed=miss_gate),data_gate_pass=pass,final_state=if(pass)"DATA_PASS_PENDING_FULL_TEXT_DEDUP"else"NO_GO_DATA_GATE")
write_json(status,file.path(out_dir,"c_n14_status.json"),pretty=TRUE,auto_unbox=TRUE,na="null");writeLines(c("# C-N14 blinded report",paste0("Actual N: ",prep$actual_n),paste0("Key group/events: ",prep$key_group_n,"/",prep$key_group_events),paste0("Adjusted PR: ",round(pr[1],3)," [",round(pr[2],3),", ",round(pr[3],3),"]"),paste0("Adjusted RD: ",round(100*rd[1],2)," pp"),paste0("Serum Na difference: ",round(nad[1],3)),paste0("Discovery/validation PR: ",round(dpr[1],3),"/",round(vpr[1],3)),paste0("State: ",status$final_state)),file.path(out_dir,"c_n14_report.md"));cat(toJSON(status,pretty=TRUE,auto_unbox=TRUE),"\n")
